version: '3.8'
services: 
    mysqldb:
     image: mysql:5.7
     container_name: mysqldb
     restart: unless-stopped
     env_file: ./.env
     environment:
      - MYSQL_ROOT_USER=$MYSQLDB_ROOT_USER
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
      - MYSQL_USER=$MYSQLDB_USER
      - MYSQL_PASSWORD=$MYSQLDB_USER_PASSWORD
     ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
     volumes:
      - db:/var/lib/mysql 
      
    backend:
     depends_on:
      - mysqldb
     container_name: backend
     build: ./01-backend
     restart: on-failure
     env_file: ./.env
     ports: 
      -  $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
     environment:
      SPRING_APPLICATION_JSON: '{
        "spring.datasource.url"  : "jdbc:mysql://mysqldb:$MYSQLDB_DOCKER_PORT/$MYSQLDB_DATABASE",
        "spring.datasource.username" : "$MYSQLDB_USER",
        "spring.datasource.password" : "$MYSQLDB_USER_PASSWORD",
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
     volumes:
      - .m2:/root/.m2
     stdin_open: true
     tty: true

volumes:
  db:
      